# Generated by Django 5.1.2 on 2024-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'クリエイター'), ('sponsor', 'スポンサー')], default='creator', max_length=10),
        ),
    ]
