on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Dylan700/sftp-upload-action@latest
        with:
          server: iis.edu.tama.ac.jp
          username: u223iwasaki
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          uploads: |
            ./html/ => ./public_html/
